services:
  - type: web
    name: student-dropout-risk-prediction
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /config
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: GRADIO_SERVER_NAME
        value: 0.0.0.0
      - key: GRADIO_ANALYTICS_ENABLED
        value: "False"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: OPENBLAS_NUM_THREADS
        value: "1"
